/* Generated By:JJTree: Do not edit this line. ArrowExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class ArrowExpr extends SimpleNode {
  public ArrowExpr(int id) {
    super(id);
  }

  public ArrowExpr(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b3488c39d2e8a5f169ad2fdbbb41252 (do not edit this line) */
