/* Generated By:JJTree: Do not edit this line. BooleanLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class BooleanLiteral extends SimpleNode {
  public BooleanLiteral(int id) {
    super(id);
  }

  public BooleanLiteral(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
    return "\"" + this.jjtGetValue().toString() + "\" (BooleanLiteral)";
  }
}
/* JavaCC - OriginalChecksum=1e50813555670eb6611a106ae4635b64 (do not edit this line) */
