/* Generated By:JJTree: Do not edit this line. CardLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

import javacc.util.Operator;

public
class CardLiteral extends SimpleNode {
  public CardLiteral(int id) {
    super(id);
  }

  public CardLiteral(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
    return children[0].toString() + " of " + children[1].toString() + " (CardLiteral)" ;
  }
}
/* JavaCC - OriginalChecksum=bf108cc20ac1469b10a964dc1e3ce658 (do not edit this line) */
