/* Generated By:JJTree: Do not edit this line. CompareExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class CompareExpr extends SimpleNode {
  public CompareExpr(int id) {
    super(id);
  }
  
  public CompareExpr(FlipParser p, int id) {
    super(p, id);
  }
  
  
  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {
    
    return
            visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e37c7ba66571897b1559646387b9cef4 (do not edit this line) */
