/* Generated By:JJTree: Do not edit this line. ConditionDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class ConditionDeclaration extends SimpleNode {
  public ConditionDeclaration(int id) {
    super(id);
  }

  public ConditionDeclaration(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e1d0491f9ebaf4be00b3d893a0b6985d (do not edit this line) */
