/* Generated By:JJTree: Do not edit this line. ElseIfStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class ElseIfStatement extends SimpleNode {
  public ElseIfStatement(int id) {
    super(id);
  }

  public ElseIfStatement(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dc340cef0464e22ad06b8c8f3b30fe3d (do not edit this line) */
