/* Generated By:JJTree: Do not edit this line. FunctionPredefined.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class FunctionPredefined extends SimpleNode {
  public FunctionPredefined(int id) {
    super(id);
  }

  public FunctionPredefined(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=82f41d96975b34f720358d33e9d846aa (do not edit this line) */
