/* Generated By:JJTree: Do not edit this line. PlayerDef.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class PlayerDef extends SimpleNode {
  public PlayerDef(int id) {
    super(id);
  }

  public PlayerDef(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e5565e736fc21a61f1af26bc2bbe295 (do not edit this line) */
