/* Generated By:JJTree: Do not edit this line. PlayerCount.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class PlayerCount extends SimpleNode {
  public PlayerCount(int id) {
    super(id);
  }

  public PlayerCount(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7453c9c0a297c1845ee3c86bcadba7d6 (do not edit this line) */
