/* Generated By:JJTree: Do not edit this line. UnaryOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.generated;

public
class UnaryOperator extends SimpleNode {
  public UnaryOperator(int id) {
    super(id);
  }

  public UnaryOperator(FlipParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlipParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=83ec40e8c36ee26200ca7e22db7042b9 (do not edit this line) */
